<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\bin\</BaseOutputPath>
    <ApplicationIcon>MackMulti.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="MackMulti.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BanchoSharp" Version="1.5.0" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="osu.NET" Version="0.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MackMultiBot.Bancho\MackMultiBot.Bancho.csproj" />
    <ProjectReference Include="..\MackMultiBot.Database\MackMultiBot.Database.csproj" />
    <ProjectReference Include="..\MackMultiBot.Logging\MackMultiBot.Logging.csproj" />
    <ProjectReference Include="..\MackMultiBot.OsuData\MackMultiBot.OsuData.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Update="MessengerApp.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
